local coord_parse = require "coord_parse"

describe("coord_parse.parse", function()
  it("parses comma-separated coordinates", function()
    local lat, lon = coord_parse.parse("23.8103, 90.4125")
    assert.near(23.8103, lat, 1e-9)
    assert.near(90.4125, lon, 1e-9)
  end)

  it("parses whitespace-separated coordinates", function()
    local lat, lon = coord_parse.parse("23.8103   90.4125")
    assert.near(23.8103, lat, 1e-9)
    assert.near(90.4125, lon, 1e-9)
  end)

  it("tolerates surrounding whitespace and negatives", function()
    local lat, lon = coord_parse.parse("  -33.8688,151.2093  ")
    assert.near(-33.8688, lat, 1e-9)
    assert.near(151.2093, lon, 1e-9)
  end)

  it("rejects a latitude beyond ±90", function()
    local lat, err = coord_parse.parse("91.0, 10.0")
    assert.is_nil(lat)
    assert.is_string(err)
  end)

  it("rejects a longitude beyond ±180", function()
    local lat, err = coord_parse.parse("10.0, 200.0")
    assert.is_nil(lat)
    assert.is_string(err)
  end)

  it("rejects unparseable text", function()
    local lat, err = coord_parse.parse("somewhere nice")
    assert.is_nil(lat)
    assert.is_string(err)
  end)

  it("rejects a single number", function()
    local lat, err = coord_parse.parse("23.8103")
    assert.is_nil(lat)
    assert.is_string(err)
  end)

  it("rejects non-strings", function()
    local lat, err = coord_parse.parse(nil)
    assert.is_nil(lat)
    assert.is_string(err)
  end)
end)
